# Generated by Django 4.2.30 on 2026-05-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomerObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=255)),
                (
                    "occupation",
                    models.CharField(
                        choices=[
                            ("professional", "Professional"),
                            ("student", "Student"),
                            ("unemployed", "Unemployed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "ordered_item",
                    models.CharField(
                        choices=[
                            ("coffee", "Coffee"),
                            ("tea", "Tea"),
                            ("juice", "Juice"),
                        ],
                        max_length=20,
                    ),
                ),
                ("time_order_placed", models.IntegerField()),
                ("time_order_received", models.IntegerField()),
                ("rating", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
